CI:add debian build
analogdevicesinc/libad9166-iio pull request #20
Opened 2023-07-28 09:09 UTC by ccraluca

Add debian Bullseye build in Azure CI

2023-08-09 15:04 UTC, SRaus requested changes

2023-08-09 15:04 UTC, SRaus commented on CI/travis/ci-linux.sh
> +	pip install -r requirements_dev.txt
There are mixed "_pip install <package_name>_" with "_python3.5 -m pip install <package_name>_". In most of the cases they should do the same thing, but also may generate errors whenever there are multiple versions of python, or PATH variable is not set properly (you can see some answers here: [https://stackoverflow.com/questions/40392499/why-is-m-needed-for-python-m-pip-install](https://stackoverflow.com/questions/40392499/why-is-m-needed-for-python-m-pip-install))

2023-08-11 10:57 UTC, ccraluca commented
I split the ci-linux.sh script into two parts and the centos part will be added in the next updates since it is not related to this PR.

2023-08-16 10:57 UTC, SRaus approved these changes

2023-08-16 11:56 UTC, merged